============================= test session starts =============================
platform win32 -- Python 3.10.16, pytest-8.4.0, pluggy-1.6.0 -- C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\Vassoura
configfile: pyproject.toml
plugins: anyio-4.9.0
collecting ... collected 0 items / 1 error

=================================== ERRORS ====================================
_____________ ERROR collecting vassoura/tests/test_heuristics.py ______________
ImportError while importing test module 'C:\Users\JM\Documents\0_CienciaDados\1_Frameworks\Vassoura\vassoura\tests\test_heuristics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\site-packages\_pytest\python.py:497: in importtestmodule
    mod = import_path(
C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\site-packages\_pytest\pathlib.py:587: in import_path
    importlib.import_module(module_name)
C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
C:\Users\JM\AppData\Local\anaconda3\envs\ENV_STONE\lib\site-packages\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
vassoura\tests\test_heuristics.py:28: in <module>
    from heuristics import (
E   ModuleNotFoundError: No module named 'heuristics'
=========================== short test summary info ===========================
ERROR vassoura/tests/test_heuristics.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.85s ===============================
